from pydantic import BaseModel

class ChatMessageRequest(BaseModel):
    message: str

class ChatMessageResponse(BaseModel):
    response: str

class HealthDataRequest(BaseModel):
    recent_symptoms: list = []
    recent_weight_logs: list = []
    # Add other relevant fields as needed

class HealthAlertResponse(BaseModel):
    alert_text: str # The text generated by the AI
    # You might want to add fields for severity, title, etc. based on how you structure the AI's output